FlightBoard.Web/Controllers/TeamController.cs
using FlightBoard.Core.Services;
using FlightBoard.Data;
using FlightBoard.Service.Business;
using FlightBoard.Service.Business.DataModels;
using FlightBoard.Web.Extensions;
using FlightBoard.Web.Helpers;
using FlightBoard.Web.Models;
using FlightBoard.Web.Security;
using Lib.Web.Mvc.JQuery.JqGrid;
using Microsoft.CSharp.RuntimeBinder;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Web.Mvc;

namespace FlightBoard.Web.Controllers
{
  [FBAuthorize]
  [OutputCache(Duration = 0, NoStore = true, VaryByParam = "*")]
  public class TeamController : BaseController
  {
    public ActionResult Index()
    {
      using (new UserService())
      {
        this.Session["ItemName"] = (object) null;
        this.Session["Contract"] = (object) null;
        this.Session["FromDate"] = (object) null;
        this.Session["ToDate"] = (object) null;
        this.Session["EventDate"] = (object) null;
        this.Session["EventEndDate"] = (object) null;
        return (ActionResult) this.View((object) new TeamModel());
      }
    }

    [HttpPost]
    public ActionResult Save(TeamModel teamModel, string StartDate, string EndDate)
    {
      using (TeamService teamService = new TeamService())
      {
        //try
        //{
        //  teamModel.IsActive = true;
        //  teamModel.CreatedDate = new DateTime?(DateTime.Now);
        //  teamModel.CreatedBy = new int?(SessionPersister.UserId);
        //  teamModel.TeamStartDate = DateTime.ParseExact(StartDate, "MM/dd/yyyy", (IFormatProvider) CultureInfo.InvariantCulture);
        //  DateTime teamStartDate = teamModel.TeamStartDate;
        //  this.ModelState.Remove("TeamStartDate");
        //  teamModel.TeamEndDate = DateTime.ParseExact(EndDate, "MM/dd/yyyy", (IFormatProvider) CultureInfo.InvariantCulture);
        //  DateTime teamEndDate = teamModel.TeamEndDate;
        //  this.ModelState.Remove("TeamEndDate");
        //  if (this.ModelState.IsValid)
        //  {
        //    ((BusinessServiceBase<fb_Teams>) teamService).Add(MappedExtensions.ToEntity(teamModel), true);
        //  }
        //  else
        //  {
        //    this.ModelState.AddModelError("", "Invalid details.");
        //    TeamModel teamModel1 = new TeamModel();
        //    using (UserService userService = new UserService())
        //    {
        //      ParameterExpression parameterExpression;
        //      // ISSUE: method reference
        //      IEnumerable<UserModel> enumerable = MappedExtensions.ToModels<fb_Users, UserModel>((IEnumerable<fb_Users>) Queryable.OrderBy<fb_Users, string>(((BusinessServiceBase<fb_Users>) userService).FindAll(), Expression.Lambda<Func<fb_Users, string>>((Expression) Expression.Property((Expression) parameterExpression, (MethodInfo) MethodBase.GetMethodFromHandle(__methodref (fb_Users.get_UserName))), new ParameterExpression[1]
        //      {
        //        parameterExpression
        //      })));
        //      // ISSUE: reference to a compiler-generated field
        //      if (TeamController.\u003CSave\u003Eo__SiteContainer0.\u003C\u003Ep__Site1 == null)
        //      {
        //        // ISSUE: reference to a compiler-generated field
        //        TeamController.\u003CSave\u003Eo__SiteContainer0.\u003C\u003Ep__Site1 = CallSite<Func<CallSite, object, IEnumerable<UserModel>, object>>.Create(Microsoft.CSharp.RuntimeBinder.Binder.SetMember(CSharpBinderFlags.None, "items", typeof (TeamController), (IEnumerable<CSharpArgumentInfo>) new CSharpArgumentInfo[2]
        //        {
        //          CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, (string) null),
        //          CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.UseCompileTimeType, (string) null)
        //        }));
        //      }
        //      // ISSUE: reference to a compiler-generated field
        //      // ISSUE: reference to a compiler-generated field
        //      object obj = TeamController.\u003CSave\u003Eo__SiteContainer0.\u003C\u003Ep__Site1.Target((CallSite) TeamController.\u003CSave\u003Eo__SiteContainer0.\u003C\u003Ep__Site1, this.ViewBag, enumerable);
        //    }
        //    return (ActionResult) this.View((object) teamModel);
        //  }
        //}
        //catch (Exception ex)
        //{
        //  ((Log4NetLoggerService) LoggerService.logger).Error(ex);
        //  return (ActionResult) this.RedirectToAction("Index");
        //}
      }
      return (ActionResult) this.Json((object) new
      {
        status = "success",
        code = "",
        message = "Team assignment completed successfully."
      });
    }

    public ActionResult AssignTeam()
    {
      TeamModel teamModel = new TeamModel();
      try
      {
        object obj1 = this.TempData["Message"];
        using (UserService userService = new UserService())
        {
          ParameterExpression parameterExpression1;
          ParameterExpression parameterExpression2;
          // ISSUE: method reference
          // ISSUE: method reference
          //IEnumerable<UserModel> enumerable = MappedExtensions.ToModels<fb_Users, UserModel>((IEnumerable<fb_Users>) Queryable.OrderBy<fb_Users, string>(Queryable.Where<fb_Users>(((BusinessServiceBase<fb_Users>) userService).FindAll(), Expression.Lambda<Func<fb_Users, bool>>((Expression) Expression.Equal((Expression) Expression.Property((Expression) parameterExpression1, (MethodInfo) MethodBase.GetMethodFromHandle(__methodref (fb_Users.get_RoleId))), (Expression) Expression.Constant((object) 3, typeof (int))), new ParameterExpression[1]
          //{
          //  parameterExpression1
          //})), Expression.Lambda<Func<fb_Users, string>>((Expression) Expression.Property((Expression) parameterExpression2, (MethodInfo) MethodBase.GetMethodFromHandle(__methodref (fb_Users.get_UserName))), new ParameterExpression[1]
          //{
          //  parameterExpression2
          //})));
          // ISSUE: reference to a compiler-generated field
          //if (TeamController.\u003CAssignTeam\u003Eo__SiteContainer2.\u003C\u003Ep__Site3 == null)
          //{
          //  // ISSUE: reference to a compiler-generated field
          //  TeamController.\u003CAssignTeam\u003Eo__SiteContainer2.\u003C\u003Ep__Site3 = CallSite<Func<CallSite, object, IEnumerable<UserModel>, object>>.Create(Microsoft.CSharp.RuntimeBinder.Binder.SetMember(CSharpBinderFlags.None, "items", typeof (TeamController), (IEnumerable<CSharpArgumentInfo>) new CSharpArgumentInfo[2]
          //  {
          //    CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, (string) null),
          //    CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.UseCompileTimeType, (string) null)
          //  }));
          //}
          //// ISSUE: reference to a compiler-generated field
          //// ISSUE: reference to a compiler-generated field
          //object obj2 = TeamController.\u003CAssignTeam\u003Eo__SiteContainer2.\u003C\u003Ep__Site3.Target((CallSite) TeamController.\u003CAssignTeam\u003Eo__SiteContainer2.\u003C\u003Ep__Site3, this.ViewBag, enumerable);
        }
      }
      catch (Exception ex)
      {
        ((Log4NetLoggerService) LoggerService.logger).Error(ex);
        this.ModelState.AddModelError("", ex.Message.ToString());
      }
      return (ActionResult) this.View((object) teamModel);
    }

    [AcceptVerbs(HttpVerbs.Post)]
    public ActionResult Find(JqGridRequest request, string TeamName, string TeamLeadName)
    {
      using (TeamService teamService = new TeamService())
      {
        try
        {
          //IQueryable<fb_Teams_Data> queryForGrid = teamService.GetQueryForGrid(TeamName, TeamLeadName);
          //JqGridResponse jqGridResponse = JqGridHelper.createJQGridResponse(Queryable.Count<fb_Teams_Data>(queryForGrid), request);
          //string str = string.Format("{0} {1}", (object) request.get_SortingName(), (object) request.get_SortingOrder());
          //int count = request.get_PageIndex() * request.get_RecordsCount();
          //int recordsCount = request.get_RecordsCount();
          //jqGridResponse.get_Records().AddRange((IEnumerable<JqGridRecord>) Enumerable.Select<fb_Teams_Data, JqGridRecord<fb_Teams_View>>((IEnumerable<fb_Teams_Data>) Enumerable.ToList<fb_Teams_Data>((IEnumerable<fb_Teams_Data>) Queryable.Take<fb_Teams_Data>(Queryable.Skip<fb_Teams_Data>((IQueryable<fb_Teams_Data>) DynamicQueryable.OrderBy<fb_Teams_Data>((IQueryable<M0>) queryForGrid, str, new object[0]), count), recordsCount)), (Func<fb_Teams_Data, JqGridRecord<fb_Teams_View>>) (p => new JqGridRecord<fb_Teams_View>(Convert.ToString(p.get_TeamId()), MappedExtensions.ToModel(p)))));
          //JqGridJsonResult jqGridJsonResult = new JqGridJsonResult();
          //((JsonResult) jqGridJsonResult).Data = (object) jqGridResponse;
          // return (ActionResult) jqGridJsonResult;
          // return null;
        }
        catch (Exception ex)
        {
          this._loggerService.Error(ex);
          return (ActionResult) this.RedirectToAction("Index");
        }
      }
      return null;
    }

    public ActionResult Edit(int id)
    {
      // ISSUE: object of a compiler-generated type is created
      // ISSUE: variable of a compiler-generated type
      //TeamController.\u003C\u003Ec__DisplayClass9 cDisplayClass9 = new TeamController.\u003C\u003Ec__DisplayClass9();
      //// ISSUE: reference to a compiler-generated field
      //cDisplayClass9.id = id;
      //using (TeamService teamService = new TeamService())
      //{
      //  // ISSUE: reference to a compiler-generated field
      //  TeamModel teamModel1 = MappedExtensions.ToModel(teamService.FindByID(cDisplayClass9.id));
      //  object obj1 = this.TempData["Message"];
      //  using (UserService userService = new UserService())
      //  {

FlightBoard.Web/Views/Team/AssignTeam.cshtml
@model FlightBoard.Web.Models.TeamModel

@using Lib.Web.Mvc.JQuery.JqGrid;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="headerWrapper">
    <ul class="tabedNav">
        <li><a href="@Url.Action("Index","Team")">Search Teams</a></li>
        <li class="active"><a href="@Url.Action("AssignTeam","Team")">Create Teams</a></li>
    </ul>
</div>
<div class="itemSearchContaier">
    <div class="itemSearchInnerContainer">
        @using (Html.BeginForm("Save", "Team", FormMethod.Post, new { @id = "form1" }))
        {
            @Html.ValidationSummary(true)
            <div class="assignTeam">
                <div class="itemSearchTop">
                    <div class="horizantalForm">
                        <label>Team Name</label>
                        @Html.TextBoxFor(x => x.TeamName)
                        @Html.ValidationMessageFor(x => x.TeamName)
                    </div>
                    <div class="horizantalForm">
                        <label>Team Leader</label>
                        @Html.DropDownListFor(x => x.TeamLeadId, @Model.TeamLeadList, new {@class="select" })
                    </div>
                    <div class="horizantalForm">
                        <label>Production From </label>
                        <div class="calendarInput">
                            @Html.TextBoxFor(x => x.TeamStartDate, "{0:MM/dd/yyyy}", new { @class = "TeamStartDate" })
                            <span id="spanfrom" class="icon calendar"></span>@*@Html.ValidationMessageFor(x => x.TeamStartDate)*@
                        </div>
                    </div>
                    <div class="horizantalForm">
                        <label>Production To </label>
                        <div class="calendarInput">
                            @Html.TextBoxFor(x => x.TeamEndDate, "{0:MM/dd/yyyy}", new { @class = "TeamStartDate" })
                            <span id="spanto" class="icon calendar"></span>@*@Html.ValidationMessageFor(x => x.TeamEndDate)*@
                        </div>
                    </div>
                </div>
                <div class="rightSideFields">
                    <label>Team Members</label>
                    <div class="fieldsWrapper">
                        <div class="checkboxMain">
                            @{int i = 1;
                            foreach (var item in ViewBag.items)
                            {
                                <div class="checkbox">
                                    <input type="checkbox" id="chkMember_@i" value="@item.UserId" name="radio-inline" />
                                    <label for="chkMember_@i">@item.FirstName @item.LastName</label>
                                </div>
                                i++;
                            }
                            }
                        </div>
                    </div>
                </div>
                <div class="btWrapper marB20"><input type="submit" value="Create Team"  /></div>
            </div>
        }
    </div>
</div>
<script type="text/javascript">

    $('#spanfrom').click(function () {
        $('#TeamStartDate').datepicker('show');
    });

    $('#spanto').click(function () {
        $('#TeamEndDate').datepicker('show');
    });

    $(document).ready(function () {

        $("#TeamStartDate").datepicker({ dateFormat: 'mm/dd/yy' }).val('');

        $("#TeamEndDate").datepicker({ dateFormat: 'mm/dd/yy' }).val('');

        $("input#TeamStartDate").inputmask("99/99/9999", { placeholder: "MM/DD/YYYY", clearIncomplete: true });

        $("input#TeamEndDate").inputmask("99/99/9999", { placeholder: "MM/DD/YYYY", clearIncomplete: true });

        $("#form1").submit(function (e) {
            e.preventDefault();
            if ($('.checkboxMain div').find("input:checked").length > 0) {

                if ($('#TeamName').val() == "") {
                    alert("Please enter Team Name"); return false;
                }
                else if ($('#TeamLeadId').val() <= 0)
                { alert("Please select Team Leader"); return false; }
                else if ($('#TeamStartDate').val() == "")
                { alert("Please select or enter Production From Date"); return false; }
                else if ($('#TeamEndDate').val() == "")
                { alert("Please select or enter Production To Date"); return false; }
                else if (!ValidateStartDate())
                { return false; }
               

                var teamInfo = new Object();
                teamInfo.TeamName = $('#TeamName').val();
                teamInfo.TeamLeadId = $('#TeamLeadId').val();
                teamInfo.TeamStartDate = $('#TeamStartDate').val();
                teamInfo.TeamEndDate = $('#TeamEndDate').val();

                var TeammemberList1 = new Array();
                $('.checkboxMain div').each(function () {
                    if ($(this).find('input:checkbox').is(':checked')) {
                        var teamMemberItem = new Object();
                        teamMemberItem.TeamMemberId = $(this).find('input:checkbox').val();
                        TeammemberList1.push(teamMemberItem);
                    }
                });
                teamInfo.fb_TeamMembers = TeammemberList1;
                $("")
                $.ajax({
                    url: "@Url.Action("Save", "Team")",
                    contentType: "application/json",
                    dataType: "json",
                    data: JSON.stringify({
                        teamModel: teamInfo,
                        StartDate: $("#TeamStartDate").val(),
                        EndDate: $("#TeamEndDate").val(),
                    }),
                    type: 'POST',
                    success: function (data) {
                        if (data.status == "success") {
                            alert(data.message);
                            window.location = '@Url.Action("Index","Team")';
                        }
                        else {
                            alert(data.data);
                        }
                    },
                    error: function (data) {
                        alert(data);
                    }
                });
            }
            else {
                alert("Please select atleast a team member.");
                return false;
            }
        });
    });

    function ValidateStartDate() {
        SDate = $("#TeamStartDate").val().split('/')[1] + "/" + $("#TeamStartDate").val().split('/')[0] + "/" + $("#TeamStartDate").val().split('/')[2];
        EDate = $("#TeamEndDate").val().split('/')[1] + "/" + $("#TeamEndDate").val().split('/')[0] + "/" + $("#TeamEndDate").val().split('/')[2];


        var rtn = true;
        if (SDate) {

            //var today = new Date(GetCurrentDate().split('/').reverse().join('/')); //+ " " + GetCurrentDateTime() //new Date(); // It's returning with time.             
            var sdattmp = new Date(SDate.split('/').reverse().join('/'));
            //alert(SDate);
            //// Compare with current Date.
            //if (sdattmp < today) {
            //    alert('Production From Date must be current or future date only.');
            //    $("#TeamStartDate").val(GetCurrentDate());
            //    rtn = false;
            //}
            // Compare with End Date.
            if (EDate) {
                var edattmp = new Date(EDate.split('/').reverse().join('/'));

                if (sdattmp > edattmp) {
                    alert('Production From Date must be same or earlier than Production To Date');
                    rtn = false;
                }
            }

        }
        return rtn;
    }



    function GetCurrentDate() {
        var ltoday = new Date();
        var lMonth = (parseInt(ltoday.getMonth()) + 1);
        var CurDate = ltoday.getDate() + "/" + ('0' + lMonth).slice(-2) + "/" + ltoday.getFullYear();
        return CurDate;
    }
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/inputmask")
}

FlightBoard.Web/Views/Team/Edit.cshtml
@model FlightBoard.Web.Models.TeamModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Edit";
}
@using (Html.BeginForm("Edit", "Team", FormMethod.Post, new { @id = "form1" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(m => m.TeamId)
    <div class="headerWrapper">
    <ul class="tabedNav">
        <li><a href="@Url.Action("Index","Team")">Search Teams</a></li>
        <li class="active"><a href="@Url.Action("AssignTeam","Team")">Create Teams</a></li>
    </ul>
</div>
    <div class="itemSearchContaier">
        <div class="itemSearchInnerContainer">
            @Html.ValidationSummary(true)
            <div class="assignTeam">
                <div class="itemSearchTop">
                    <div class="horizantalForm">
                        <label>Team Name</label>
                        @Html.TextBoxFor(x => x.TeamName)
                        @Html.ValidationMessageFor(x => x.TeamName)
                    </div>
                    <div class="horizantalForm">
                        <label>Team Leader</label>
                        @Html.DropDownListFor(x => x.TeamLeadId, @Model.TeamLeadList)
                    </div>
                    <div class="horizantalForm">
                        <label>Production From</label>
                        <div class="calendarInput">
                            @Html.TextBoxFor(x => x.TeamStartDate, "{0:MM/dd/yyyy}", new { @value = "", @class = "TeamStartDate" })
                            <span class="icon calendar"></span>@*@Html.ValidationMessageFor(x => x.TeamStartDate)*@
                        </div>
                    </div>
                    <div class="horizantalForm">
                        <label>Production To</label>
                        <div class="calendarInput">
                            @Html.TextBoxFor(x => x.TeamEndDate, "{0:MM/dd/yyyy}", new { @value = "", @class = "TeamStartDate" })
                            <span class="icon calendar"></span>@*@Html.ValidationMessageFor(x => x.TeamEndDate)*@
                        </div>
                    </div>
                </div>
                <div class="rightSideFields">
                    <label>Team Members</label>
                    <div class="fieldsWrapper">
                        <div class="checkboxMain">
                            @{int i = 1;
                            foreach (var item in ViewBag.items)
                            {
                                if (Model.TeammemberList.Contains(item.UserId))
                                {
                                    <div class="checkbox">
                                        <input type="checkbox" id="chkMember_@i" checked="checked" value="@item.UserId" name="radio-inline" />
                                        <label for="chkMember_@i">@item.FirstName @item.LastName</label>
                                    </div>
                                }
                                else
                                {
                                    <div class="checkbox">
                                        <input type="checkbox" id="chkMember_@i" value="@item.UserId" name="radio-inline" />
                                        <label for="chkMember_@i">@item.FirstName @item.LastName</label>
                                    </div>
                                }
                                i++;
                            }
                            }
                        </div>
                    </div>
                </div>
                <div class="btWrapper">
                    <input name="" type="reset" class="button medium" value="Cancel" onclick="location.href='@Url.Action("Index", "Team")'" />
                    <input name="" type="submit" class="button medium marR10" value="Update" />
                </div>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {

        $("#TeamStartDate").datepicker({ dateFormat: 'mm/dd/yy', defaultDate: new Date() });
        $("#TeamEndDate").datepicker({ dateFormat: 'mm/dd/yy', defaultDate: new Date() });

        $("#form1").submit(function (e) {
            e.preventDefault();
            if ($('.checkboxMain div').find("input:checked").length > 0) {

                if ($('#TeamName').val() == "") {
                    alert("Please enter Team Name"); return false;
                }
                else if ($('#TeamLeadId').val() <= 0)
                { alert("Please select Team Leader"); return false; }
                else if ($('#TeamStartDate').val() == "")
                { alert("Please select or enter Production From Date"); return false; }
                else if ($('#TeamEndDate').val() == "")
                { alert("Please select or enter Production To Date"); return false; }
                else if (!ValidateStartDate())
                { return false; }
               
                //$('#TeamStartDate').val($("#TeamStartDate").val().split('/')[1] + "/" + $("#TeamStartDate").val().split('/')[0] + "/" + $("#TeamStartDate").val().split('/')[2])
                //$('#TeamEndDate').val($("#TeamEndDate").val().split('/')[1] + "/" + $("#TeamEndDate").val().split('/')[0] + "/" + $("#TeamEndDate").val().split('/')[2])

                var teamInfo = new Object();
                teamInfo.TeamName = $('#TeamName').val();
                teamInfo.TeamLeadId = $('#TeamLeadId').val();
                teamInfo.TeamStartDate = $('#TeamStartDate').val();
                teamInfo.TeamEndDate = $('#TeamEndDate').val();
                teamInfo.TeamId = $('#TeamId').val();

                var TeammemberList1 = new Array();
                $('.checkboxMain div').each(function () {
                    if ($(this).find('input:checkbox').is(':checked')) {
                        var teamMemberItem = new Object();
                        teamMemberItem.TeamMemberId = $(this).find('input:checkbox').val();
                        teamMemberItem.TeamId = $('#TeamId').val();
                        TeammemberList1.push(teamMemberItem);
                    }
                });
                teamInfo.fb_TeamMembers = TeammemberList1;
                $.blockUI();
                $.ajax({
                    url: "@Url.Action("Edit", "Team")",
                    contentType: "application/json",
                    dataType: "json",
                    data: JSON.stringify({
                        teamModel: teamInfo,
                        StartDate: $("#TeamStartDate").val(),
                        EndDate: $("#TeamEndDate").val(),
                    }),
                    type: 'POST',
                    success: function (data) {
                        if (data.status == "success") {
                            $.unblockUI();
                            window.location = "@Url.Action("Index", "Team")";
                            //alert("Data Inserted Successfully.")
                            }
                        else {
                            alert(data.data);
                            $.unblockUI();
                        }
                    },
                    error: function (e, textStatus, jqXHR) {
                        $.unblockUI();
                    }
                });
            }
            else {
                alert("Please select atleast one teammember.");
                return false;
            }
        });
    });


    function ValidateStartDate() {
        SDate = $("#TeamStartDate").val().split('/')[1] + "/" + $("#TeamStartDate").val().split('/')[0] + "/" + $("#TeamStartDate").val().split('/')[2];
        EDate = $("#TeamEndDate").val().split('/')[1] + "/" + $("#TeamEndDate").val().split('/')[0] + "/" + $("#TeamEndDate").val().split('/')[2];

        
        var rtn = true;
        if (SDate) {

            //var today = new Date(GetCurrentDate().split('/').reverse().join('/')); //+ " " + GetCurrentDateTime() //new Date(); // It's returning with time.             
            var sdattmp = new Date(SDate.split('/').reverse().join('/'));
            //alert(SDate);
            //// Compare with current Date.
            //if (sdattmp < today) {
            //    alert('Production From Date must be current or future date only.');
            //    $("#TeamStartDate").val(GetCurrentDate());
            //    rtn = false;
            //}
            // Compare with End Date.
            if (EDate) {
                var edattmp = new Date(EDate.split('/').reverse().join('/'));
                
                if (sdattmp > edattmp) {
                    alert('Production From Date must be same or earlier than Production To Date');
                    rtn = false;
                }
            }
           
        }
        return rtn;
    }

    

    function GetCurrentDate() {
        var ltoday = new Date();
        var lMonth = (parseInt(ltoday.getMonth()) + 1);
        var CurDate = ltoday.getDate() + "/" + ('0' + lMonth).slice(-2) + "/" + ltoday.getFullYear();
        return CurDate;
    }

</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}